# -------------------------------------------------------------------------------------
# Customizing Output Formats
# See: https://gohugo.io/templates/output-formats/#customizing-output-formats
# -------------------------------------------------------------------------------------

  _merge = "shadow"
  home = ["html", "rss", "jsonfeed", "archives", "offline", "search"]
  page = ["html", "markdown"]
  section = ["html", "rss", "jsonfeed"]
  taxonomy = ["html"]
  term = ["html", "rss", "jsonfeed"]
