# -------------------------------------------------------------------------------------
# Hugo Configuration
# See: https://gohugo.io/getting-started/configuration/
# -------------------------------------------------------------------------------------

title = "Hugo FixIt Blog"
baseURL = "/"
# theme = "FixIt"
defaultContentLanguage = "en"
languageCode = "en"
hasCJKLanguage = true
enableRobotsTXT = false
enableEmoji = true
enableGitInfo = true
relativeURLs = true
buildDrafts = true
summaryLength = 150
# ignore some build errors
ignoreLogs = [
  "error-get-remote-image",
  "error-get-remote-json",
  "error-remote-getjson",
  "error-missing-instagram-accesstoken"
]
